### ISSUE TITLE
Also support transforming non-standard origin?

### ISSUE THREAD

**Issue by patrickarlt** [aximgeo/arcgis-level-fixer#5]
Cross posting this with the Esri Leaflet issue.

Over the weekend I got a support request from the City of Philadelphia who has the following tile service http://tiles.arcgis.com/tiles/fLeGjb7u4uXqeF9q/arcgis/rest/services/CityBasemap_2015/MapServer with non standard zoom levels AND a non-standard origin [-20037700, 30241100] vs [-20037508.342787, 20037508.342787]. The zoom level correction code is working great but all the tile values are offset because of the custom origin.

@jonahadkins @cbupp @jgravois what do you think about trying to make Esri Leaflet/Arcgis Level Fixer also handle custom origins? How difficult would that be?

https://github.com/Esri/esri-leaflet/issues/567

**Comment by patrickarlt** [comment]
As an example

Correct Tile
http://tiles2.arcgis.com/tiles/fLeGjb7u4uXqeF9q/arcgis/rest/services/CityBasemap_2015/MapServer/tile/6/41509/19087

Currently Requested Tile
http://tiles2.arcgis.com/tiles/fLeGjb7u4uXqeF9q/arcgis/rest/services/CityBasemap_2015/MapServer/tile/6/24821/19085

**Comment by cbupp** [comment]
@patrickarlt do you think it would be as simple modifying the x/y in the URL? (i.e. could be handled with a simple HTTP redirect)

It looks like it might be more complicated than that: It may require grabbing 4 tiles, and cropping and joining them and re-serving the new tile. (which this would end up being a fun task)

**Comment by patrickarlt** [comment]
Crap I didn't think about it that way. This would require basically cutting up and re-serving the whole tile set  if the origin was off enough, which it probably is so this is out of scope for both this project and Esri Leaflet.

**Comment by cbupp** [comment]
Out of scope maybe for Esri-Leaflet... but this proxy project does already scrape and server non-tiled Image Services into tiles... so, it's not entirely out of the realm of possibility for this project :)

**Comment by cbupp** [comment]
http://tiles.arcgis.com/tiles/fLeGjb7u4uXqeF9q/arcgis/rest/services/CityBasemap_2015/MapServer/tile/0/648/298

almost maps to

http://tiles.arcgis.com/tiles/fLeGjb7u4uXqeF9q/arcgis/rest/services/CityBasemap_2015/MapServer/tile/0/648/298

Digging into this issue further, the Origin.x is nearly correct, while the Y offset is almost 1.5 times larger than, resulting in not only a tile index shift, but also results in requiring 2-4 tiles to recreate the new tile.

**Comment by cbupp** [comment]
@patrickarlt 

This functionality has been added to ALF v0.3.2. You can test it out here: http://gisinc.github.io/arcgis-level-fixer/

This fix creates and serves new tiles on the server.

**Comment by patrickarlt** [comment]
@cbupp this is fantastic! Works great http://jsbin.com/nisogabogo/edit?html,output. Thank you.
